var bounds = new google.maps.LatLngBounds();
const bounds_follows_pin = true;
var markers = [];

$(document).ready(async function () {
	console.log("Loading...");
	$("body").prepend("<div id='loading'><div class='spinner'></div> Loading...</div>");

	var script = document.createElement('script');
	script.src = "https://appulance.com/mapbuilder/js/infobox.js";
	document.head.appendChild(script);

	var hospitals_js = document.createElement('script');
	hospitals_js.src = "https://appulance.com/mapbuilder/hospitals/hospitals.js";
	document.head.appendChild(hospitals_js);

	var stations_js = document.createElement('script');
	stations_js.src = "https://appulance.com/mapbuilder/stations/stations.js";
	document.head.appendChild(stations_js);

	var styles_js = document.createElement('script');
	styles_js.src = "https://appulance.com/mapbuilder/styles.js";
	document.head.appendChild(styles_js);

	await sleep(400);

	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-60890786-8', 'auto');
	ga('set', 'checkProtocolTask', null); // Disable file protocol checking.
	ga('set', 'checkStorageTask', null); // Disable cookie storage checking.
	ga('set', 'historyImportTask', null); // Disable history checking (requires reading from cookies).
	ga(function(tracker) {
 		localStorage.setItem(someKey, tracker.get('clientId'));
	})
	ga('set', 'page', 'mapViewWithPOI');
	ga('send', 'pageview');


	var mapOptions = {
    	zoom: 2,
		center: new google.maps.LatLng(0, 0),
		styles: styles['default'],
		streetViewControl: false,
		mapTypeControlOptions: { mapTypeIds: [google.maps.MapTypeId.ROADMAP, google.maps.MapTypeId.HYBRID] }
	}
	map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

	// add markers to markers[]. called from HTML generated by Excel
	addMarkers();

	markers = markers.sort((a, b) => {
		return a.serial - b.serial;
	});

	addMarkersToTimeline(markers);
	addMarkersToAliases(markers);
	$("#map-form").show();

	HospitalsIterator();
	StationsIterator();

	// add info box
    $("#map-form").append("<div id='info'></div>");
	$("#info").hide();

	$("#timeline").change(function() {
		selected = $(this).val(); 
		selected_alias = $("#aliases").val();
		selected_times_count = $(this).val().length;

		ga('send', 'event', 'Timeline', 'Time Selected');

		if (bounds_follows_pin) {
			bounds = new google.maps.LatLngBounds();
		}

		for (var i = 0; i < markers.length; i++) {
			current = markers[i].serial.toString();
			current_alias = markers[i].alias.toString();
			label_id = "#infobox-" + markers[i].serial + "-" + markers[i].alias;

			if (selected.includes(current) == true && selected_alias.includes(current_alias)) {
				markers[i].setVisible(true);

				// zoom to pin?
				bounds.extend(markers[i].position);

				// show label for this pin
				if (label_status) $(label_id).show();

				if (selected_times_count == 1) {
					tooltip = markers[i].title.replace(/\n/g, "<br />");
					$("#info").html(tooltip);
					$("#info").show();
				} else if (selected_times_count != 1) {
					$("#info").hide();
				}
			} else {
				markers[i].setVisible(false);
				if (label_status) $(label_id).hide();
			}
		}

		if (bounds_follows_pin) {
			var originalMaxZoom = map.maxZoom;
			map.setOptions({maxZoom: 15});
			map.fitBounds(bounds);
			map.setOptions({maxZoom: originalMaxZoom});
		} else {
			map.fitBounds(bounds, 500);
		}
	});

	var label_status = $("#label-toggle").is(":checked");
	var night_status = $("#night-toggle").is(":checked");

	$("#label-toggle").change(function() {
		label_status = $("#label-toggle").is(":checked");

		if (label_status == true) {
			let selected_aliases = $("#aliases").val();
			let selected_times = $("#timeline").val();
			console.log(selected_aliases);
			console.log(selected_times);

			for (var i = 0; i < selected_aliases.length; i++) {
				for (var j = 0; j < selected_times.length; j++) {
					var infobox = "#infobox-"+ selected_times[j] + "-" + selected_aliases[i];
					$(infobox).show();
				}
			}
		} else  {
			// otherwise hide
			$(".infobox").hide();
		}
	});

	$("#night-toggle").change(function() {
		night_status = $("#night-toggle").is(":checked");

		if (night_status == true) {
			// check what aliases and timelines are selected, and show them
			map.setOptions({ styles: styles['dark'] });
			$("#map-form").css('color', 'white');
		} else  {
			// otherwise hide
			map.setOptions({ styles: styles['default'] });
			$("#map-form").css('color', 'black');
		}
	});

	$("#aliases").change(function() {
        selected = $(this).val(); 
		bounds = new google.maps.LatLngBounds();
		$("#timeline").empty(); 

		ga('send', 'event', 'Aliases', 'Alias Change');

		for (var i = 0; i < markers.length; i++) {
			current = markers[i].alias; 
			label_id = "#infobox-" + markers[i].serial + "-" + markers[i].alias;

			if (selected.includes(current) == true) {
				markers[i].setVisible(true);

				if (label_status) $(label_id).show();
					// reset bounds to group of related pins
					bounds.extend(markers[i].position);

					serial = markers[i].serial;
					datetime = new Date(markers[i].serial);
					addTimelineEntryToTimeline(datetime, serial);
					//$('#timeline').append(new Option(datetime.toLocaleDateString("en-AU") + " " + datetime.toLocaleTimeString("en-AU"), serial, true, true));
				} else {
					markers[i].setVisible(false);
					if (label_status) $(label_id).hide();
				}
			}
			
			// zoom to selected pins
			map.fitBounds(bounds);
		});
		
		google.maps.event.addListener(map, "idle", function() {
			$("#loading").hide();
		});		
});

Object.defineProperty(String.prototype, 'hashCode', {
	// string -> hash
	value: function() {
		var hash = 0, i, chr;
		for (i = 0; i < this.length; i++) {
			chr = this.charCodeAt(i);
			hash  = ((hash << 5) - hash) + chr;
			hash |= 0; // Convert to 32bit integer
		}

    	return hash;
	}
});

var stringToColour = function(str) {
	// string to colour
	// in this instance we use the hashed string

	var hash = 0;
	for (var i = 0; i < str.length; i++) {
		hash = str.charCodeAt(i) + ((hash << 5) - hash);
	}
	var colour = '#';
	for (var i = 0; i < 3; i++) {
		var value = (hash >> (i * 8)) & 0xFF;
		colour += ('00' + value.toString(16)).substr(-2);
	}
	return colour;
}

function getMarkerURLWithLabel (str, lab) {
	var color = stringToColour(str).substr(1);
    return "http://www.googlemapsmarkers.com/v1/" + "test" + "/" + "FFFFFF" + "/"  + color + "/" + ldColour(color, 40) + "/";
}

function getMarkerURL(str) {
	var color = stringToColour(str).substr(1);
	return "http://www.googlemapsmarkers.com/v1/" + "0" + "/" + color + "/"  + color + "/" + ldColour(color, 40) + "/";
}

function ldColour(col,amt) {
	// lighten hex colour
    var usePound = false;
    if ( col[0] == "#" ) {
        col = col.slice(1);
        usePound = true;
    }

    var num = parseInt(col,16);

    var r = (num >> 16) + amt;

    if ( r > 255 ) r = 255;
    else if  (r < 0) r = 0;

    var b = ((num >> 8) & 0x00FF) + amt;

    if ( b > 255 ) b = 255;
    else if  (b < 0) b = 0;

    var g = (num & 0x0000FF) + amt;

    if ( g > 255 ) g = 255;
    else if  ( g < 0 ) g = 0;

    return (usePound?"#":"") + (g | (b << 8) | (r << 16)).toString(16);
}

function invertColor(hex, bw) {
    if (hex.indexOf('#') === 0) {
        hex = hex.slice(1);
    }
    // convert 3-digit hex to 6-digits.
    if (hex.length === 3) {
        hex = hex[0] + hex[0] + hex[1] + hex[1] + hex[2] + hex[2];
    }
    if (hex.length !== 6) {
        throw new Error('Invalid HEX color.');
    }
    var r = parseInt(hex.slice(0, 2), 16),
        g = parseInt(hex.slice(2, 4), 16),
        b = parseInt(hex.slice(4, 6), 16);
    if (bw) {
        // http://stackoverflow.com/a/3943023/112731
        return (r * 0.299 + g * 0.587 + b * 0.114) > 186
            ? '#000000'
            : '#FFFFFF';
    }
    // invert color components
    r = (255 - r).toString(16);
    g = (255 - g).toString(16);
    b = (255 - b).toString(16);
    // pad each with zeros and return
    return "#" + padZero(r) + padZero(g) + padZero(b);
}

function addMarker(lat, lon, datetime, alias="Single", label = "", color = "blue") {
	var position = new google.maps.LatLng(lat, lon);

	var date = new Date(datetime);
	var time = date.toLocaleString([], { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false });
	var pinUrl = getMarkerURL(alias);
	var serial = date.getTime();
	var colour = stringToColour(alias);
	var lightened_colour = ldColour(colour, 40);
	alias = alias.toString();

	if (markers.some(el => el.alias === alias && el.serial === serial)) {
		// we don't want duplicate markers, so
		// if marker already exists, return
		return;
	} 

	ga('send', 'event', 'Markers', 'Add Marker');

	let marker = new google.maps.Marker({
		map: map,
		position: position,
		icon: {
			url: pinUrl,
		},
		serial: serial,
		alias: alias,
		title: label,
		date: date.toLocaleDateString()
	});

	let infobox = new InfoBox({
		content: time,
		boxClass: "infobox infobox-" + alias + " infobox-" + serial,
		boxId: "infobox-" + serial + "-" + alias,
		boxStyle: {
			"background-color": colour,
			"width": "50px",
			"color": invertColor(colour, true),
			"border-color": lightened_colour
		},
		disableAutoPan: true,
		pixelOffset: new google.maps.Size(-31, -32),
		position: position,
		closeBoxURL: "",
		isHidden: false,
		pane: "floatPane",
		enableEventPropagation: false,
	});

	marker.addListener("click", () => {
		markerClickHandler(marker.serial, marker.alias);
	});

	//store the marker object drawn in global array
	markers.push(marker);
	infobox.open(map);

	// zoom viewport
	bounds.extend(position);
	map.fitBounds(bounds);
}

function markerClickHandler(serial, alias="Single") {
	ga('send', 'event', 'Markers', 'Marker Clicked');

	$("#aliases").val([]);
	$('#aliases option[value="' + alias + '"]').prop("selected", true).change();

	$("#timeline").val([]);
	$("#timeline option[value='" + serial + "']").prop("selected", true).change();

	scrollToOption($("#aliases"), alias);
	scrollToOption($("#timeline"), serial);

	$("#timeline").focus();
	$("#timeline option[value='" + serial + "']").select();
	$("#timeline option[value='" + serial + "']").focus();
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function resetSelectElement(el) {
	el.selectedIndex = 0;  // first option is selected, or
                               // -1 for no option selected
}

async function scrollToOption(select, value) {
	await sleep(100);
	var options = select.find("option");
	var option = select.find("option[value='" + value + "']");
	var optionTop = option.offset().top
	var selectTop = select.offset().top;
	select.scrollTop(select.scrollTop() + (optionTop - selectTop) - 20);
}

/*function sortMarkers(arr) {
	var save = Object.prototype.toString;
	Object.prototype.toString = function () { return this.key; };

	arr.sort((a, b) => {
		return a.serial - b.serial;
	})
	.filter((v,i,a) => {
		a.findIndex(t=>(t.alias === v.alias && t.serial === v.serial))===i
	});

	Object.prototype.toString = save;

	return arr;
}

function deDupeMarkers(arr) {
	var save = Object.prototype.toString;
	Object.prototype.toString = function () { return this.key; };

	arr.filter((v,i,a) => {
		a.findIndex(t=>(t.alias === v.alias && t.serial === v.serial))===i
	});

	Object.prototype.toString = save;

	return arr;
}*/

function addMarkersToTimeline(arr) {
	$("#timeline").parent().prepend("<button id='timeline-all' type='button'>Select All Times for Vehicle</button>");
	$("#timeline").parent().prepend("<hr/>");
	$("#timeline").parent().prepend("<select multiple id='dates'>Select All Times for Vehicle</select>");
	$("#timeline").parent().prepend("<button id='dates-all' type='button'>Select All Dates</button>");
	$("#timeline").parent().prepend("<hr/>");

	$("#timeline-all").on('click', function() {
		ga('send', 'event', 'Timeline', 'Select All');
		$("select#timeline >  option").prop("selected", true);
		$("select#timeline").change();
	});

	var dates = arr.reduce((acc, current) => {
		x = acc.find(item => item.date === current.date);
		if (!x) {
			return acc.concat([current]);
  		} else {
    			return acc;
  		}
	}, []);

	for (var i = 0; i < dates.length; i++) {
		date = dates[i].date;
		addDateEntryToTimeline(date, date, $("#dates"));
	}

	for (var i = 0; i < arr.length; i++) {
		serial = arr[i].serial;
		datetime = new Date(serial);
		addTimelineEntryToTimeline(datetime, serial);
		//$('#timeline').append(new Option(datetime.toLocaleDateString("en-AU") + " " + datetime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }), serial, true, true));
	}
}

function addDateEntryToTimeline(date, serial, timeline = $("#dates"), sel = true) {
	let entry = new Option(date, date, sel, sel);
	timeline.append(entry);
}

function addTimelineEntryToTimeline(datetime, serial, timeline = $("#timeline"), sel = true) {
	let string = datetime.toLocaleDateString("en-AU") + " " + datetime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false })
	let entry = new Option(string, serial, sel, sel);
	timeline.append(entry);
}

function addMarkersToAliases(arr) {
	// we only want to show unique aliases, so remove all duplicates
	var aliases = arr.reduce((acc, current) => {
		x = acc.find(item => item.alias === current.alias);
		if (!x) {
			return acc.concat([current]);
  		} else {
    			return acc;
  		}
	}, []);

	$("<hr/>").insertBefore("#aliases");
    $("<button id='aliases-all' type='button'>Select All Vehicles</button>").insertBefore("#aliases");
	$("#aliases").parent().prepend("<div id='label-toggle-container'><label for='label-toggle'><input type='checkbox' id='label-toggle' /> Show labels?</label></div>");

	$("#aliases").parent().prepend("<div id='night-toggle-container'><label for='night-toggle'><input type='checkbox' id='night-toggle' /> Dark mode?</label></div>");

	$("#aliases-all").on('click', function() {
		ga('send', 'event', 'Aliases', 'Select All');
		$("select#aliases >  option").prop("selected", true);
		$("select#aliases").change();
	});

	for (var i = 0; i < aliases.length; i++) {
	//	console.log(arr[i].alias);
		alias = aliases[i].alias;
		$('#aliases').append(new Option(alias, alias, true, true));
	}
}

function getPinColourByHour(hour) {
	if (hour > 6 && hour < 18) {
		// if day shift
		return "blue";
	} else {
		return "red";
	}
}

function getPinUrlByHour(hour) {
	colour = getPinColourByHour(hour);
	var url = "http://maps.google.com/mapfiles/ms/icons/";
	url += colour + "-dot.png";

	return url;
}



